# Generated by Django 3.1.1 on 2021-04-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KombinasiSoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_kombinasi', models.ImageField(upload_to='img/kombinasi')),
            ],
        ),
    ]
