# Generated by Django 3.1.1 on 2021-04-25 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_kombinasisoal_no_kombinasi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KombinasiSoal',
        ),
    ]
